ALTER TYPE "WorkspaceHistoryAction" RENAME VALUE 'MEMBER_JOINED' TO 'WORKSPACE_INVITE_ACCEPTED';
ALTER TYPE "WorkspaceHistoryAction" ADD VALUE IF NOT EXISTS 'WORKSPACE_INVITE_CREATED';
ALTER TYPE "WorkspaceHistoryAction" ADD VALUE IF NOT EXISTS 'WORKSPACE_INVITE_REJECTED';
ALTER TYPE "WorkspaceHistoryAction" ADD VALUE IF NOT EXISTS 'WORKSPACE_INVITE_CANCELLED';
