export enum WorkspaceHistoryEvent {
  ITEM_CREATED = 'item.created',
  ITEM_UPDATED = 'item.updated',
  ITEM_DELETED = 'item.deleted',
  PAYMENT_CREATED = 'payment.created',
  PAYMENT_UPDATED = 'payment.updated',
  PAYMENT_DELETED = 'payment.deleted',
  TAG_CREATED = 'tag.created',
  TAG_UPDATED = 'tag.updated',
  TAG_DELETED = 'tag.deleted',
  ITEM_TAG_ASSIGNED = 'item_tag.assigned',
  ITEM_TAG_UNASSIGNED = 'item_tag.unassigned',
  WORKSPACE_CREATED = 'workspace.created',
  WORKSPACE_UPDATED = 'workspace.updated',
  WORKSPACE_DELETED = 'workspace.deleted',
  ITEM_MERGED = 'item.merged',
}
