export enum WorkspaceHistoryEvent {
  ITEM_CREATED = 'item.created',
  ITEM_UPDATED = 'item.updated',
  ITEM_DELETED = 'item.deleted',
  PAYMENT_CREATED = 'payment.created',
  PAYMENT_UPDATED = 'payment.updated',
  PAYMENT_DELETED = 'payment.deleted',
  TAG_CREATED = 'tag.created',
  TAG_UPDATED = 'tag.updated',
  TAG_DELETED = 'tag.deleted',
  ITEM_TAG_ASSIGNED = 'item_tag.assigned',
  ITEM_TAG_UNASSIGNED = 'item_tag.unassigned',
  WORKSPACE_CREATED = 'workspace.created',
  WORKSPACE_UPDATED = 'workspace.updated',
  WORKSPACE_DELETED = 'workspace.deleted',
  ITEM_MERGED = 'item.merged',
  ITEM_EXTRACTED = 'item.extracted',
  WORKSPACE_INVITE_CREATED = 'workspace_invite.created',
  WORKSPACE_INVITE_ACCEPTED = 'workspace_invite.accepted',
  WORKSPACE_INVITE_REJECTED = 'workspace_invite.rejected',
  WORKSPACE_INVITE_CANCELLED = 'workspace_invite.cancelled',
  WORKSPACE_MEMBER_CREATED = 'workspace_member.created',
  WORKSPACE_MEMBER_REMOVED = 'workspace_member.removed',
  ITEM_STAKE_CREATED = 'item_stake.created',
  ITEM_STAKE_UPDATED = 'item_stake.updated',
}
